In [3]:
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)

print(x)

27


In [7]:
# Generate a random float from 0 to 1:
x = random.rand()

print(x)

0.712616763758148


In [8]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
x=random.randint(100, size=(5))

print(x)

[ 0 36 92 89 44]


In [10]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))

print(x)

[[58 91 18 16 14]
 [85 56 66 53 42]
 [36 99 56 91 76]]


choice()

In [18]:
# Return one of the values in an array:
x = random.choice([3, 5, 7, 9])

print(x)

9


In [19]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 5 3 9 3]
 [5 3 7 9 5]
 [5 3 9 9 5]]


Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

In [20]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 3 7 5 5 3 7 7 5 7 7 7 3 5 7 5 7 5 7 7 7 5 3 3 7 5 7 7 7 5 7 7 5 5 7 7
 7 7 7 5 7 5 7 5 5 3 5 7 3 7 5 5 5 3 3 5 5 7 7 7 7 7 5 7 7 7 7 7 7 5 7 5 7
 5 3 3 5 7 7 7 7 7 3 7 7 5 5 3 5 5 7 7 7 3 3 3 3 7 7]


In [22]:
# Same example as above, but return a 2-D array with 3 rows, each containing 5 values.
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 7 7 3]
 [7 7 7 7 5]
 [7 5 7 7 5]]
