# What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.  
# What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

In [1]:
# Without ufunc, we can use Python's built-in zip() method:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [2]:
# With ufunc, we can use the add() function:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


# Create Your Own ufunc

In [3]:
# Create your own ufunc for addition:

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [5]:
print(type(myadd))
print(type(np.add))

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


In [8]:
# Check the type of another function: concatenate():

print(type(np.concatenate))
# print(type(np.blahblah))

<class 'numpy._ArrayFunctionDispatcher'>


In [9]:
# Use an if statement to check if the function is a ufunc or not:

if type(np.add) is np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


# Simple Arithmetic
You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.  
**Arithmetic Conditionally**: means that we can define conditions where the arithmetic operation should happen.

## Addition

In [10]:
# Add the values in arr1 to the values in arr2:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


## Subtraction

In [11]:
# Subtract the values in arr2 from the values in arr1:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


## Multiplication

In [12]:
# Multiply the values in arr1 with the values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


## Division

In [13]:
# Divide the values in arr1 with the values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


## Power

In [14]:
# Raise the valules in arr1 to the power of values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


## Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [16]:
# Return the remainders:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
print(newarr)

newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


## Quotient and Mod
The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [17]:
# Return the quotient and mod:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [19]:
# Return the absolute positive values of arr:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

- truncation
- fix
- rounding
- floor
- ceil

## Truncation
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [2]:
# Truncate elements of following array:
import numpy as np
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [3]:
# Same example, using fix():
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


## Rounding
The `around()` function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2

In [4]:
# Round off 3.1666 to 2 decimal places:
arr = np.around(3.1666, 2)

print(arr)

3.17


## Floor
The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.

In [5]:
# Floor the elements of following array:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


## Ceil
The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 4.

In [6]:
# Ceil the elements of following array:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


# Logs
NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.

In [7]:
# Find log at base 2 of all elements of following array:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [8]:
# Find log at base 10 of all elements of following array:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [9]:
# Find log at base e of all elements of following array:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


# Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [11]:
from math import log

nplog = np.frompyfunc(log, 2, 1)

print(nplog(27, 3))

3.0


# Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [12]:
# Add the values in arr1 to the values in arr2:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [13]:
# Sum the values in arr1 and the values in arr2:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


If you specify axis=1, NumPy will sum the numbers in each array.

In [14]:
# Perform summation in the following array over 1st axis:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


## Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [21]:
# Perform cummulative summation in the following array:
arr = np.array([1, 2, 3, 4])

newarr = np.cumsum(arr)

print(newarr)

[ 1  3  6 10]


# Products
To find the product of the elements in an array, use the prod() function.

In [16]:
# Find the product of the elements of this array:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [18]:
# Find the product of the elements of two arrays:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)
print(1*2*3*4*5*6*7*8)

40320
40320


In [19]:
# If you specify axis=1, NumPy will return the product of each array.
# Perform summation in the following array over 1st axis:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


## Cummulative Product
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the `cumprod()` function.

In [20]:
# Take cummulative product of all elements for following array:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


# Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [22]:
# Compute discrete difference of the following array:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


We can perform this operation repeatedly by giving parameter `n`.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

In [23]:
# Compute discrete difference of the following array twice:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]
